global using Microsoft.AspNetCore.Http;
global using System.Security.Claims;
global using FreeSql;
global using AutoMapper;
global using TTMS.Enums;
global using TTMS.Domain;
global using TTMS.DTO.Request;
global using TTMS.DTO.Response;
global using TTMS.Utility;
